# Docs: https://goreleaser.com/customization/builds/
project_name: sdk

builds:
  - id: "sdk"
    binary: "sdk"
    main: ./cli
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
      - openbsd
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "6"
      - "7"
    ldflags:
      - -s
      - -w
      - -X main.version={{ .Version }}
      - -X main.revision={{ .FullCommit }}
      - -X main.buildDate={{ .Date }}

source:
  enabled: true
  name_template: "{{ .ProjectName }}-{{ .Version }}"
  prefix_template: "{{ .ProjectName }}-{{ .Version }}/"

checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}.sha256"
  algorithm: sha256

# signs:
#   - artifacts: checksum
#     args:
#       [
#         "--batch",
#         "-u",
#         "{{ .Env.GPG_FINGERPRINT }}",
#         "--output",
#         "${signature}",
#         "--detach-sign",
#         "${artifact}",
#       ]

docker_manifests:
  - name_template: ghcr.io/succinctlabs/sdk:v{{ .Version }}
    image_templates:
      - ghcr.io/succinctlabs/sdk:v{{ .Version }}-amd64
      - ghcr.io/succinctlabs/sdk:v{{ .Version }}-arm64v8
      - ghcr.io/succinctlabs/sdk:v{{ .Version }}-arm32v7
      - ghcr.io/succinctlabs/sdk:v{{ .Version }}-arm32v6
  - name_template: ghcr.io/succinctlabs/sdk:v{{ .Major }}.{{ .Minor }}
    image_templates:
      - ghcr.io/succinctlabs/sdk:v{{ .Major }}.{{ .Minor }}-amd64
      - ghcr.io/succinctlabs/sdk:v{{ .Major }}.{{ .Minor }}-arm64v8
      - ghcr.io/succinctlabs/sdk:v{{ .Major }}.{{ .Minor }}-arm32v7
      - ghcr.io/succinctlabs/sdk:v{{ .Major }}.{{ .Minor }}-arm32v6
  - name_template: ghcr.io/succinctlabs/sdk:latest
    image_templates:
      - ghcr.io/succinctlabs/sdk:latest-amd64
      - ghcr.io/succinctlabs/sdk:latest-arm64v8
      - ghcr.io/succinctlabs/sdk:latest-arm32v7
      - ghcr.io/succinctlabs/sdk:latest-arm32v6
  - name_template: ghcr.io/succinctlabs/sdk:nightly
    image_templates:
      - ghcr.io/succinctlabs/sdk:nightly-amd64
      - ghcr.io/succinctlabs/sdk:nightly-arm64v8
      - ghcr.io/succinctlabs/sdk:nightly-arm32v7
      - ghcr.io/succinctlabs/sdk:nightly-arm32v6

dockers:
  - image_templates:
      - ghcr.io/succinctlabs/sdk:v{{ .Version }}-amd64
      - ghcr.io/succinctlabs/sdk:v{{ .Major }}.{{ .Minor }}-amd64
      - ghcr.io/succinctlabs/sdk:latest-amd64
      - ghcr.io/succinctlabs/sdk:nightly-amd64
    ids: ["sdk"]
    goarch: amd64
    build_flag_templates:
      - --build-arg=BINARY_NAME=sdk
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title=sdk
      - --label=org.opencontainers.image.description=sdk
      - --label=org.opencontainers.image.url=https://github.com/succinctlabs/sdk
      - --label=org.opencontainers.image.source=https://github.com/succinctlabs/sdk
      - --label=org.opencontainers.image.version=v{{ .Version }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
    dockerfile: Dockerfile.release
    use: buildx
  - image_templates:
      - ghcr.io/succinctlabs/sdk:v{{ .Version }}-arm64v8
      - ghcr.io/succinctlabs/sdk:v{{ .Major }}.{{ .Minor }}-arm64v8
      - ghcr.io/succinctlabs/sdk:latest-arm64v8
      - ghcr.io/succinctlabs/sdk:nightly-arm64v8
    ids: ["sdk"]
    goarch: arm64
    build_flag_templates:
      - --build-arg=BINARY_NAME=sdk
      - --platform=linux/arm64/v8
      - --label=org.opencontainers.image.title=sdk
      - --label=org.opencontainers.image.description=sdk
      - --label=org.opencontainers.image.url=https://github.com/succinctlabs/sdk
      - --label=org.opencontainers.image.source=https://github.com/succinctlabs/sdk
      - --label=org.opencontainers.image.version=v{{ .Version }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
    dockerfile: Dockerfile.release
    use: buildx
  - image_templates:
      - ghcr.io/succinctlabs/sdk:v{{ .Version }}-arm32v7
      - ghcr.io/succinctlabs/sdk:v{{ .Major }}.{{ .Minor }}-arm32v7
      - ghcr.io/succinctlabs/sdk:latest-arm32v7
      - ghcr.io/succinctlabs/sdk:nightly-arm32v7
    ids: ["sdk"]
    goarch: arm
    goarm: "7"
    build_flag_templates:
      - --build-arg=BINARY_NAME=sdk
      - --platform=linux/arm/v7
      - --label=org.opencontainers.image.title=sdk
      - --label=org.opencontainers.image.description=sdk
      - --label=org.opencontainers.image.url=https://github.com/succinctlabs/sdk
      - --label=org.opencontainers.image.source=https://github.com/succinctlabs/sdk
      - --label=org.opencontainers.image.version=v{{ .Version }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
    dockerfile: Dockerfile.release
    use: buildx
  - image_templates:
      - ghcr.io/succinctlabs/sdk:v{{ .Version }}-arm32v6
      - ghcr.io/succinctlabs/sdk:v{{ .Major }}.{{ .Minor }}-arm32v6
      - ghcr.io/succinctlabs/sdk:latest-arm32v6
      - ghcr.io/succinctlabs/sdk:nightly-arm32v6
    ids: ["sdk"]
    goarch: arm
    goarm: "6"
    build_flag_templates:
      - --build-arg=BINARY_NAME=sdk
      - --platform=linux/arm/v6
      - --label=org.opencontainers.image.title=sdk
      - --label=org.opencontainers.image.description=sdk
      - --label=org.opencontainers.image.url=https://github.com/succinctlabs/sdk
      - --label=org.opencontainers.image.source=https://github.com/succinctlabs/sdk
      - --label=org.opencontainers.image.version=v{{ .Version }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
    dockerfile: Dockerfile.release
    use: buildx

release:
  name_template: "v{{ .Version }}"
  footer: |
    * * *
    Having trouble? Open an [issue](https://github.com/succinctlabs/sdk/issues/new) on Github.
    Other thoughts? Come participate with the community on [Twitter](https://twitter.com/succinctlabs) or [Discord](https://discord.gg/succinctlabs).
