// AUTOGENERATED: DO NOT TOUCH
package main

import (
	"github.com/consensys/gnark/frontend"
	"github.com/succinctlabs/sdk/gnarkx/vars"
)

type Circuit struct {
	InputBytes  []vars.Byte
	OutputBytes []vars.Byte
}

func (circuit *Circuit) GetInputBytes() *[]vars.Byte {
	return &circuit.InputBytes
}

func (circuit *Circuit) GetOutputBytes() *[]vars.Byte {
	return &circuit.OutputBytes
}

func NewCircuit() *Circuit {
	circuit := &Circuit{}
	circuit.InputBytes = vars.NewBytes(32)
	circuit.OutputBytes = vars.NewBytes(32)
	return circuit
}

func (circuit *Circuit) SetWitness(inputBytes []byte) {
}

func (circuit *Circuit) Assign(inputBytes []byte) error {
	vars.SetBytes(&circuit.InputBytes, inputBytes)
	vars.SetBytes(&circuit.OutputBytes, make([]byte, 32))

	return nil
}

func (circuit *Circuit) Define(BaseApi frontend.API) error {
	return nil
}
