// // AUTOGENERATED: DO NOT TOUCH
// package main

// import (
// 	"github.com/succinctlabs/sdk/gnarkx/succinct"
// )

// func main() {
// 	succinct.Run(NewCircuit())
// }

pub use plonky2x::CircuitFunction;
pub use crate::my_circuit::*;

pub fn main() {
    let args: Vec<String> = env::args().collect();
    CircuitFunction.run(my_circuit, args)
}