name: Go Release

on:
  push:
    branches-ignore:
      - "**"
    tags:
      - "v*.*.*"

permissions:
  contents: write
  packages: write

jobs:
  test:
    name: Release
    runs-on: chad

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.PRIVATE_PULL_TOKEN }}

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u succinctlabs --password-stdin

      #   - name: Import GPG key
      #     id: import_gpg
      #     uses: crazy-max/ghaction-import-gpg@v5
      #     with:
      #       gpg_private_key: ${{ secrets.GPG_SIGNING_KEY }}
      #       passphrase: ${{ secrets.GPG_PASSPHRASE }}
      #
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #   GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
